batch_size: 128
checkpoint_dir: checkpoints_poj104_pretrained
checkpoint_per_epoch: 1
clip_gradient: null
normalization: null
dataset_paths:
  test: datasets/POJ104/test
  train: datasets/POJ104/train
  val: datasets/POJ104/val
dropout_rate: 0.1
early_stopping:
  patience: 8
epochs: 100
etypes:
- control_flow_edge
- next_stmt_edge
- ast_edge
- data_flow_edge
in_channels: 512
log_dir: logs_poj104_pretrained
n_classes: 1000
num_layers: 1
num_graph_heads: 8
num_graph_steps: 8
old_checkpoint_path: ''
optimizer:
  name: Adam
  params:
    lr: 0.0000001
out_channels: 512
scheduler:
  name: OneCycleLR
  params:
    max_lr: 0.0001
    epochs: 30
    steps_per_epoch: 1
    anneal_strategy: linear
time_steps:
- 2
- 2
- 1
- 2
- 1
vocab:
  node_token: vocab/OJ104-order-node-token.txt
  node_type: vocab/OJ104-order-node-type.txt
