batch_size: 128
checkpoint_dir: checkpoints_cpp1000_scratch
checkpoint_per_epoch: 1
clip_gradient: null
normalization: null
dataset_paths:
  test: datasets/C++1000/test
  train: datasets/C++1000/train
  val: datasets/C++1000/val
  classmapping: datasets/C++1000/metadata/C_1000_class_mapping.json
dropout_rate: 0.3
early_stopping:
  patience: 8
epochs: 100
etypes:
- control_flow_edge
- next_stmt_edge
- ast_edge
- data_flow_edge
in_channels: 128
log_dir: logs_cpp1000_scratch
n_classes: 1000
num_layers: 1
num_graph_heads: 8
num_graph_steps: 8
old_checkpoint_path: ''
optimizer:
  name: Adam
  params:
    lr: 0.0001
out_channels: 128
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 8
    eta_min: 1.0e-06
time_steps:
- 3
- 1
- 3
- 1
vocab:
  node_token: vocab/C++1000_node_tokens_.txt
  node_type: vocab/C++1000_node_types_.txt